name: Build Workflow

on:
  push
    branches:
      - main

jobs:
  bluid:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Run un bluid
        run: echo "bluid"