name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Run un test
        run: echo "Franck"